### ISSUE TITLE
After merge groovydoc task for stub-runner-spring throws NoClassDefFoundError

### ISSUE THREAD

**Issue by szpak** [4finance/micro-infra-spring#149]
After merge `stub-runner:stub-runner-spring:groovydoc` throws exception:

```
:stub-runner:stub-runner-spring:groovydoc
[ant:groovydoc] javassist.CannotCompileException: by java.lang.NoClassDefFoundError: org/apache/zookeeper/server/SessionTracker$SessionExpirer
[ant:groovydoc] 	at javassist.ClassPool.toClass(ClassPool.java:1099)
[ant:groovydoc] 	at javassist.ClassPool.toClass(ClassPool.java:1042)
[ant:groovydoc] 	at javassist.ClassPool.toClass(ClassPool.java:1000)
[ant:groovydoc] 	at javassist.CtClass.toClass(CtClass.java:1224)
[ant:groovydoc] 	at org.apache.curator.test.ByteCodeRewrite.fixMethods(ByteCodeRewrite.java:95)
[ant:groovydoc] 	at org.apache.curator.test.ByteCodeRewrite.<clinit>(ByteCodeRewrite.java:50)
[ant:groovydoc] 	at org.apache.curator.test.TestingServer.<clinit>(TestingServer.java:33)
[ant:groovydoc] 	at java.lang.Class.forName0(Native Method)
[ant:groovydoc] 	at java.lang.Class.forName(Class.java:260)
[ant:groovydoc] 	at org.codehaus.groovy.tools.groovydoc.SimpleGroovyClassDoc.resolveExternalClassFromImport(SimpleGroovyClassDoc.java:650)
[ant:groovydoc] 	at org.codehaus.groovy.tools.groovydoc.SimpleGroovyClassDoc.resolveClass(SimpleGroovyClassDoc.java:560)
[ant:groovydoc] 	at org.codehaus.groovy.tools.groovydoc.SimpleGroovyClassDoc.resolve(SimpleGroovyClassDoc.java:353)
[ant:groovydoc] 	at org.codehaus.groovy.tools.groovydoc.SimpleGroovyRootDoc.resolve(SimpleGroovyRootDoc.java:145)
[ant:groovydoc] 	at 
(...)
[ant:groovydoc] 	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:246)
[ant:groovydoc] 	at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
[ant:groovydoc] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[ant:groovydoc] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[ant:groovydoc] 	at java.lang.Thread.run(Thread.java:745)
[ant:groovydoc] Caused by: java.lang.NoClassDefFoundError: org/apache/zookeeper/server/SessionTracker$SessionExpirer
[ant:groovydoc] 	at java.lang.ClassLoader.defineClass1(Native Method)
[ant:groovydoc] 	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
[ant:groovydoc] 	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
[ant:groovydoc] 	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
[ant:groovydoc] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ant:groovydoc] 	at java.lang.reflect.Method.invoke(Method.java:483)
[ant:groovydoc] 	at javassist.ClassPool.toClass2(ClassPool.java:1112)
[ant:groovydoc] 	at javassist.ClassPool.toClass(ClassPool.java:1093)
[ant:groovydoc] 	... 121 more
[ant:groovydoc] Caused by: java.lang.ClassNotFoundException: org.apache.zookeeper.server.SessionTracker$SessionExpirer
[ant:groovydoc] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
[ant:groovydoc] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
[ant:groovydoc] 	at java.security.AccessController.doPrivileged(Native Method)
[ant:groovydoc] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
[ant:groovydoc] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[ant:groovydoc] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[ant:groovydoc] 	... 129 more

```

Build ends successfully, but there is no exception in groovydoc task called from separate `stub-runner-spring`.

**Comment by mchmielarz** [comment]
Unable to reproduce the problem on:
* Mac OSX with JDK 1.7u72 and 1.8u25
* Win7 with JDK 1.8u25
