### ISSUE TITLE
stub-runner from Gradle fails to start

### ISSUE THREAD

**Issue by nurkiewicz** [4finance/micro-infra-spring#231]
<a href="https://github.com/nurkiewicz"><img src="https://avatars.githubusercontent.com/u/164045?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [nurkiewicz](https://github.com/nurkiewicz)**
_Monday Dec 22, 2014 at 15:31 GMT_
_Originally opened as https://github.com/4finance/stub-runner/issues/25_

----

Since 1dd274d (https://github.com/4finance/stub-runner/issues/15) `gradle runStubs` fails for numerous reasons:

1) Missing now required `-n` option:

	java.lang.NullPointerException: name cannot be null
		at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:226) ~[guava-18.0.jar:na]
		at org.apache.curator.x.discovery.details.ServiceCacheImpl.<init>(ServiceCacheImpl.java:60) ~[curator-x-discovery-2.7.0.jar:na]
		at org.apache.curator.x.discovery.details.ServiceCacheBuilderImpl.build(ServiceCacheBuilderImpl.java:47) ~[curator-x-discovery-2.7.0.jar:na]
		at org.apache.curator.x.discovery.details.ServiceProviderImpl.<init>(ServiceProviderImpl.java:52) ~[curator-x-discovery-2.7.0.jar:na]
		at org.apache.curator.x.discovery.details.ServiceProviderBuilderImpl.build(ServiceProviderBuilderImpl.java:45) ~[curator-x-discovery-2.7.0.jar:na]
		at org.apache.curator.x.discovery.ServiceProviderBuilder$build$0.call(Unknown Source) ~[na:na]
		at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45) ~[groovy-all-2.3.8.jar:2.3.8]
		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108) ~[groovy-all-2.3.8.jar:2.3.8]
		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112) ~[groovy-all-2.3.8.jar:2.3.8]
		at com.ofg.stub.mapping.ProjectMetadataResolver.resolveServcieDependenciesFromZookeeper(ProjectMetadataResolver.groovy:31) ~[main/:na]

2) ZooKeeper server not started, only created (I fixed that):

	java.lang.NullPointerException: client cannot be null
		at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:226) ~[guava-18.0.jar:na]
		at org.apache.curator.x.discovery.details.ServiceDiscoveryImpl.<init>(ServiceDiscoveryImpl.java:95) ~[curator-x-discovery-2.7.0.jar:na]
		at org.apache.curator.x.discovery.ServiceDiscoveryBuilder.build(ServiceDiscoveryBuilder.java:57) ~[curator-x-discovery-2.7.0.jar:na]
		at org.apache.curator.x.discovery.ServiceDiscoveryBuilder$build$2.call(Unknown Source) ~[na:na]
		at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45) ~[groovy-all-2.3.8.jar:2.3.8]
		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108) ~[groovy-all-2.3.8.jar:2.3.8]
		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112) ~[groovy-all-2.3.8.jar:2.3.8]
		at com.ofg.stub.mapping.ProjectMetadataResolver.resolveServcieDependenciesFromZookeeper(ProjectMetadataResolver.groovy:26) ~[main/:na]

3) `stub-runner` tries to fetch projects from ZK (in `com.ofg.stub.StubRunner#resolveProjects`) before these projects are registered (in `com.ofg.stub.StubRunnerExecutor#runStubs`):

	Exception in thread "main" java.lang.NullPointerException: Cannot get property 'payload' on null object
		at org.codehaus.groovy.runtime.NullObject.getProperty(NullObject.java:57)
		at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:168)
		at org.codehaus.groovy.runtime.callsite.NullCallSite.getProperty(NullCallSite.java:44)
		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:227)
		at com.ofg.stub.mapping.ProjectMetadataResolver.resolveServcieDependenciesFromZookeeper(ProjectMetadataResolver.groovy:33)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:483)
		at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
		at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite$StaticMetaMethodSiteNoUnwrapNoCoerce.invoke(StaticMetaMethodSite.java:148)
		at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.callStatic(StaticMetaMethodSite.java:99)
		at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:53)
		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:157)
		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:173)

Maybe some of these are just configuration issues, not real bugs.

**Comment by marcingrzejszczak** [comment]
Not applicable anymore
