### ISSUE TITLE
AvailablePortScanner fails with IllegalArgumentException: bound must be positive

### ISSUE THREAD

**Issue by szpak** [4finance/micro-infra-spring#258]
Tests in stub-runner tend to hang for a moment (sometimes 10+ minutes which fails build in Travis). It is (sometimes?) reproducible locally. With `--info` enabled there is recurring (a lot of times) debug message which can be related:
```
    11:49:46.715 [Test worker] DEBUG c.o.stub.server.AvailablePortScanner - Failed to execute closure
    java.lang.IllegalArgumentException: bound must be positive
    	at java.util.Random.nextInt(Random.java:388) ~[na:1.8.0_25]
    	at org.apache.commons.lang.math.JVMRandom.nextInt(JVMRandom.java:118) ~[commons-lang-2.6.jar:2.6]
    	at org.apache.commons.lang.math.RandomUtils.nextInt(RandomUtils.java:88) ~[commons-lang-2.6.jar:2.6]
    	at org.apache.commons.lang.math.RandomUtils.nextInt(RandomUtils.java:74) ~[commons-lang-2.6.jar:2.6]
    	at com.ofg.stub.server.AvailablePortScanner.tryToExecuteWithFreePort(AvailablePortScanner.groovy:24) ~[main/:na]
    	at com.ofg.stub.server.AvailablePortScanner$tryToExecuteWithFreePort.call(Unknown Source) [main/:na]
(...)
```

It would be useful to take a look at that code to find when `bound` can be not positive.

**Comment by marcingrzejszczak** [comment]
Done in https://github.com/4finance/micro-infra-spring/commit/94a66d5af18b97ec320c61518fbc432600ea3c00
