### ISSUE TITLE
Circuit breaking not working as it should

### ISSUE THREAD

**Issue by marcingrzejszczak** [4finance/micro-infra-spring#336]
Receiving the following exception when sending a request:

```
2015-03-21 16:10:57.977+0100 | ERROR |  | http-nio-8080-exec-1 | o.a.c.c.C.[.[.[.[dispatcherServlet] | Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.ofg.infrastructure.web.resttemplate.custom.ResponseException: Status code: [404], Headers: [[Content-Length:[0], Server:[Jetty(6.1.26)]]], Body: [null]] with root cause
com.ofg.infrastructure.web.resttemplate.custom.ResponseException: Status code: [404], Headers: [[Content-Length:[0], Server:[Jetty(6.1.26)]]], Body: [null]
	at com.ofg.infrastructure.web.resttemplate.custom.ResponseRethrowingErrorHandler.handleError(ResponseRethrowingErrorHandler.groovy:27) ~[micro-infra-spring-base-0.8.14.jar:na]
	at org.springframework.web.client.RestTemplate.handleResponseError(RestTemplate.java:615) ~[spring-web-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:573) ~[spring-web-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:529) ~[spring-web-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:447) ~[spring-web-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.web.client.RestTemplate$$FastClassBySpringCGLIB$$aa4e9ed0.invoke(<generated>) ~[spring-core-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717) ~[spring-aop-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85) ~[spring-aop-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at com.ofg.infrastructure.web.resttemplate.MetricsAspect$_measureRestCallDuration_closure1.doCall(MetricsAspect.groovy:32) ~[micro-infra-spring-base-0.8.14.jar:na]
	at com.ofg.infrastructure.web.resttemplate.MetricsAspect$_measureRestCallDuration_closure1.call(MetricsAspect.groovy) ~[micro-infra-spring-base-0.8.14.jar:na]
	at com.codahale.metrics.Timer.time(Timer.java:101) ~[metrics-core-3.1.0.jar:3.1.0]
	at com.ofg.infrastructure.web.resttemplate.MetricsAspect.measureRestCallDuration(MetricsAspect.groovy:30) ~[micro-infra-spring-base-0.8.14.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_05]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_05]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_05]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_05]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:621) ~[spring-aop-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:610) ~[spring-aop-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:68) ~[spring-aop-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:97) ~[spring-aop-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at com.ofg.infrastructure.web.correlationid.CorrelationIdAspect.wrapWithCorrelationIdForRestOperations(CorrelationIdAspect.groovy:82) ~[micro-infra-spring-base-0.8.14.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_05]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_05]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_05]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_05]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:621) ~[spring-aop-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:610) ~[spring-aop-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:68) ~[spring-aop-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653) ~[spring-aop-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at com.ofg.infrastructure.web.resttemplate.custom.RestTemplate$$EnhancerBySpringCGLIB$$34370c2b.exchange(<generated>) ~[spring-core-4.1.5.RELEASE.jar:na]
	at org.springframework.web.client.RestOperations$exchange.call(Unknown Source) ~[na:na]
	at com.ofg.infrastructure.web.resttemplate.fluent.common.response.executor.RestExecutor$_urlTemplateExchange_closure1.doCall(RestExecutor.groovy:79) ~[micro-infra-spring-base-0.8.14.jar:na]
	at com.ofg.infrastructure.web.resttemplate.fluent.common.response.executor.RestExecutor$_urlTemplateExchange_closure1.doCall(RestExecutor.groovy) ~[micro-infra-spring-base-0.8.14.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_05]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_05]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_05]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_05]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90) ~[groovy-all-2.4.1.jar:2.4.1]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324) ~[groovy-all-2.4.1.jar:2.4.1]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292) ~[groovy-all-2.4.1.jar:2.4.1]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016) ~[groovy-all-2.4.1.jar:2.4.1]
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39) ~[groovy-all-2.4.1.jar:2.4.1]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:114) ~[groovy-all-2.4.1.jar:2.4.1]
	at com.ofg.infrastructure.web.resttemplate.fluent.common.response.executor.RestExecutor$1.doRun(RestExecutor.groovy:116) ~[micro-infra-spring-base-0.8.14.jar:na]
	at com.ofg.infrastructure.web.resttemplate.fluent.common.response.executor.RestExecutor$1.doRun(RestExecutor.groovy) ~[micro-infra-spring-base-0.8.14.jar:na]
	at com.ofg.infrastructure.hystrix.CorrelatedCommand$_run_closure1.doCall(CorrelatedCommand.groovy:25) ~[micro-infra-spring-base-0.8.14.jar:na]
	at com.ofg.infrastructure.hystrix.CorrelatedCommand$_run_closure1.call(CorrelatedCommand.groovy) ~[micro-infra-spring-base-0.8.14.jar:na]
	at com.ofg.infrastructure.correlationid.CorrelationIdUpdater.withId(CorrelationIdUpdater.groovy:45) ~[micro-infra-spring-base-0.8.14.jar:na]
	at com.ofg.infrastructure.hystrix.CorrelatedCommand.run(CorrelatedCommand.groovy:24) ~[micro-infra-spring-base-0.8.14.jar:na]
	at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:294) ~[hystrix-core-1.4.0-rc.9.jar:1.4.0-rc.9]
	at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:289) ~[hystrix-core-1.4.0-rc.9.jar:1.4.0-rc.9]
	at rx.Observable$1.call(Observable.java:144) ~[rxjava-1.0.7.jar:1.0.7]
	at rx.Observable$1.call(Observable.java:136) ~[rxjava-1.0.7.jar:1.0.7]
	at rx.Observable$1.call(Observable.java:144) ~[rxjava-1.0.7.jar:1.0.7]
	at rx.Observable$1.call(Observable.java:136) ~[rxjava-1.0.7.jar:1.0.7]
	at rx.Observable$1.call(Observable.java:144) ~[rxjava-1.0.7.jar:1.0.7]
	at rx.Observable$1.call(Observable.java:136) ~[rxjava-1.0.7.jar:1.0.7]
	at rx.Observable.unsafeSubscribe(Observable.java:7466) ~[rxjava-1.0.7.jar:1.0.7]
	at com.netflix.hystrix.AbstractCommand$5.call(AbstractCommand.java:514) ~[hystrix-core-1.4.0-rc.9.jar:1.4.0-rc.9]
	at com.netflix.hystrix.AbstractCommand$5.call(AbstractCommand.java:497) ~[hystrix-core-1.4.0-rc.9.jar:1.4.0-rc.9]
	at rx.Observable.unsafeSubscribe(Observable.java:7466) ~[rxjava-1.0.7.jar:1.0.7]
	at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62) ~[rxjava-1.0.7.jar:1.0.7]
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:56) ~[hystrix-core-1.4.0-rc.9.jar:1.4.0-rc.9]
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:47) ~[hystrix-core-1.4.0-rc.9.jar:1.4.0-rc.9]
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction.call(HystrixContexSchedulerAction.java:69) ~[hystrix-core-1.4.0-rc.9.jar:1.4.0-rc.9]
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:47) ~[rxjava-1.0.7.jar:1.0.7]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_05]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_05]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_05]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_05]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_05]

```

present here - https://github.com/microhackathon-2015-03-juglodz/fraud-detection-service-waw/releases/tag/issueWithCircutBreaking

**Comment by wojda** [comment]
The cause of the Exception is the type of returned value (returned by closure). In our case it was a **String**.

    ...
    .withCircuitBreaker(
      Setter
        .withGroupKey(HystrixCommandGroupKey.Factory.asKey("fraudDetection"))
        .andCommandKey(HystrixCommandKey.Factory.asKey("notifyDecisionMaker"))
      , { 'duap' }
    )

To make it works, the closure must return **ResponseEntity**:

    ...
    .withCircuitBreaker(
      Setter
        .withGroupKey(HystrixCommandGroupKey.Factory.asKey("fraudDetection"))
        .andCommandKey(HystrixCommandKey.Factory.asKey("notifyDecisionMaker"))
      , { ResponseEntity.ok('duap') }
    )

**Comment by marcingrzejszczak** [comment]
Thanks for the workaround - good to know that there is one for that!

Still we have to check out what is wrong here cause it's not working as it is supposed to.

BTW you have a typo in `'duap'` :D

**Comment by wojda** [comment]
Well, it is not a workaround. In that way this feature was designed, I suppose so. Check the spec:
[ServiceRestClientSpec](https://github.com/4finance/micro-infra-spring/blob/master/micro-infra-spring-base/src/test/groovy/com/ofg/infrastructure/web/resttemplate/fluent/ServiceRestClientSpec.groovy#L265)

There is only one place in code (micro-infra-spring) where not parameterized Closure was used. Yes, it's 
a public API (HttpMethod.groovy). In other cases Closure<ResponseEntity<T>> was used. 

From my point of view (as a user of the ServiceRestClient API), Closure which returns ResponseEntity<T> is ok. I would've known how to use that if I'd got

    HttpMethod<U, T> withCircuitBreaker(HystrixCommand.Setter setter, Closure<ResponseEntity<T>> hystrixFallback)

instead of

    HttpMethod<U, T> withCircuitBreaker(HystrixCommand.Setter setter, Closure hystrixFallback)

**Comment by marcingrzejszczak** [comment]
@wojda - it's obvious how it's designed but it's not how it should be designed :D You shouldn't need to be forced to use a `ResponseEntity`.

**Comment by marcingrzejszczak** [comment]
Fixed in https://github.com/4finance/micro-infra-spring/pull/343

I've built a local version of micro-infra-spring from this PR and I've managed to make it work with your code

```
2015-03-22 23:02:24.742+0100 | DEBUG | 73c11548-5fd6-4c46-b871-e71064871197 | hystrix-fraudDetection-1 | c.o.i.w.r.c.ResponseRethrowingErrorHandler | Exception while loading body from error response
java.io.FileNotFoundException: http://localhost:11618/api/loanApplication/1
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_05]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_05]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_05]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:408) ~[na:1.8.0_05]
        at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1888) ~[na:1.8.0_05]
        at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1883) ~[na:1.8.0_05]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_05]
        at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1882) ~[na:1.8.0_05]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1455) ~[na:1.8.0_05]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1439) ~[na:1.8.0_05]
        at org.springframework.http.client.SimpleClientHttpResponse.getBody(SimpleClientHttpResponse.java:81) ~[spring-web-4.1.5.RELEASE.jar:4.1.5.RELEASE]
        at org.springframework.http.client.BufferingClientHttpResponseWrapper.getBody(BufferingClientHttpResponseWrapper.java:69) ~[spring-web-4.1.5.RELEASE.jar:4.1.5.RELEASE]
        at com.ofg.infrastructure.web.resttemplate.custom.ResponseRethrowingErrorHandler.getResponseBody(ResponseRethrowingErrorHandler.groovy:38) [micro-infra-spring-base-0.7.888.jar:na]
        at com.ofg.infrastructure.web.resttemplate.custom.ResponseRethrowingErrorHandler.getLoggedErrorResponseBody(ResponseRethrowingErrorHandler.groovy:31) [micro-infra-spring-base-0.7.888.jar:na]
        at com.ofg.infrastructure.web.resttemplate.custom.ResponseRethrowinandler.handleError(ResponseRethrowingErrorHandler.groovy:26) [micro-infra-spring-base-0.7.888.jar:na]
        at org.springframework.web.client.RestTemplate.handleResponseError(RestTemplate.java:615) [spring-web-4.1.5.RELEASE.jar:4.1.5.RELEASE]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:573) [spring-web-4.1.5.RELEASE.jar:4.1.5.RELEASE]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:529) [spring-web-4.1.5.RELEASE.jar:4.1.5.RELEASE]
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:447) [spring-web-4.1.5.RELEASE.jar:4.1.5.RELEASE]
        at org.springframework.web.client.RestTemplate$$FastClassBySpringCGLIB$$aa4e9ed0.invoke(<generated>) [spring-core-4.1.5.RELEASE.jar:4.1.5.RELEASE]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) [spring-core-4.1.5.RELEASE.jar:4.1.5.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717) [spring-aop-4.1.5.RELEASE.jar:4.1.5.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) [spring-aop-4.1.5.RELEASE.jar:4.1.5.RELEASE]
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85) [spring-aop-4.1.5.RELEASE.jar:4.1.5.RELEASE]
        at com.ofg.infrastructure.web.resttemplate.MetricsAspect$_measureRestCallDuration_closure1.doCall(MetricsAspect.groovy:32) [micro-infra-spring-base-0.7.888.jar:na]
        at com.ofg.infrastructure.web.resttemplate.MetricsAspect$_measureRestCallDuration_closure1.call(MetricsAspect.groovy) [micro-infra-spring-base-0.7.888.jar:na]
        at com.codahale.metrics.Timer.time(Timer.java:101) [metrics-core-3.1.0.jar:3.1.0]
        at com.ofg.infrastructure.web.resttemplate.MetricsAspect.measureRestCallDuration(MetricsAspect.groovy:30) [micro-infra-spring-base-0.7.888.jar:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_05]
        at sun.reflect.NativeMethodAccessorImke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_05]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_05]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_05]
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:621) [spring-aop-4.1.5.RELEASE.jar:4.1.5.RELEASE]
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:610) [spring-aop-4.1.5.RELEASE.jar:4.1.5.RELEASE]
        at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:68) [spring-aop-4.1.5.RELEASE.jar:4.1.5.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) [spring-aop-4.1.5.RELEASE.jar:4.1.5.RELEASE]
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:97) [spring-aop-4.1.5.RELEASE.jar:4.1.5.RELEASE]
        at com.ofg.infrastructure.web.correlationid.CorrelationIdAspect.wrapWithCorrelationIdForRestOperations(CorrelationIdAspect.groovy:82) [micro-infra-spring-base-0.7.888.jar:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_05]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_05]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_05]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_05]
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:621) [spring-aop-4.1.5.RELEASE.jar:4.1.5.RELEASE]
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:610) [spring-aop-4.1.5.RELEASE.jar:4.1.5.RELEASE]
        at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:68) [spring-aop-4.1.5.RELEASE.jar:4.1.5.RELEASE]
        at org.springframework.aop.framework.ReflectiveMeocation.proceed(ReflectiveMethodInvocation.java:179) [spring-aop-4.1.5.RELEASE.jar:4.1.5.RELEASE]
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) [spring-aop-4.1.5.RELEASE.jar:4.1.5.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) [spring-aop-4.1.5.RELEASE.jar:4.1.5.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653) [spring-aop-4.1.5.RELEASE.jar:4.1.5.RELEASE]
        at com.ofg.infrastructure.web.resttemplate.custom.RestTemplate$$EnhancerBySpringCGLIB$$20940a4f.exchange(<generated>) [spring-core-4.1.5.RELEASE.jar:na]
        at org.springframework.web.client.RestOperations$exchange.call(Unknown Source) [spring-web-4.1.5.RELEASE.jar:4.1.5.RELEASE]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45) [groovy-all-2.4.1.jar:2.4.1]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:110) [groovy-all-2.4.1.jar:2.4.1]
        at com.ofg.infrastructure.web.resttemplate.fluent.common.response.executor.RestExecutor$_urlTemplateExchange_closure1.doCall(RestExecutor.groovy:79) [micro-infra-spring-base-0.7.888.jar:na]
        at com.ofg.infrastructure.web.resttemplate.fluent.common.response.executor.RestExecutor$_urlTemplateExchange_closure1.doCall(RestExecutor.groovy) [micro-infra-spring-base-0.7.888.jar:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_05]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_05]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_05]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_05]
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90) [groovy-all-2.4.1.jar:2.4.1]
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324) [groovy-all-2.4.1.jar:2.4.1]
        at org.codehaus.groovy.runtimeass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292) [groovy-all-2.4.1.jar:2.4.1]
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016) [groovy-all-2.4.1.jar:2.4.1]
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39) [groovy-all-2.4.1.jar:2.4.1]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45) [groovy-all-2.4.1.jar:2.4.1]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:110) [groovy-all-2.4.1.jar:2.4.1]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:114) [groovy-all-2.4.1.jar:2.4.1]
        at com.ofg.infrastructure.web.resttemplate.fluent.common.response.executor.RestExecutor$1.doRun(RestExecutor.groovy:116) [micro-infra-spring-base-0.7.888.jar:na]
        at com.ofg.infrastructure.web.resttemplate.fluent.common.response.executor.RestExecutor$1.doRun(RestExecutor.groovy) [micro-infra-spring-base-0.7.888.jar:na]
        at com.ofg.infrastructure.hystrix.CorrelatedCommand$_run_closure1.doCall(CorrelatedCommand.groovy:25) [micro-infra-spring-base-0.7.888.jar:na]
        at com.ofg.infrastructure.hystrix.CorrelatedCommand$_run_closure1.call(CorrelatedCommand.groovy) [micro-infra-spring-base-0.7.888.jar:na]
        at com.ofg.infrastructure.correlationid.CorrelationIdUpdater.withId(CorrelationIdUpdater.groovy:45) [micro-infra-spring-base-0.7.888.jar:na]
        at com.ofg.infrastructure.hystrix.CorrelatedCommand.run(CorrelatedCommand.groovy:24) [micro-infra-spring-base-0.7.888.jar:na]
        at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:294) [hystrix-core-1.4.0-rc.9.jar:1.4.0-rc.9]
        at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:289) [hystrix-core-1.4.0-rc.9.jar:1.4.0-rc.9]
        at rx.Observable$1.call(Observable.java:144) [rxjava-1.0.7.jar:1.0.7]
        at rx.Observable$1.call(Observable.java:136) [rxjava-1.0.7.jar:1.0.7]
        at rx.Observable$1.call(Observable.java:144) [rxjava-1.0.7.jar:1.0.7]
        at rx.Observable$1.call(Observable.java:136) [rxjava-1.0.7.jar:1.0.7]
  t rx.Observable$1.call(Observable.java:144) [rxjava-1.0.7.jar:1.0.7]
        at rx.Observable$1.call(Observable.java:136) [rxjava-1.0.7.jar:1.0.7]
        at rx.Observable.unsafeSubscribe(Observable.java:7466) [rxjava-1.0.7.jar:1.0.7]
        at com.netflix.hystrix.AbstractCommand$5.call(AbstractCommand.java:514) [hystrix-core-1.4.0-rc.9.jar:1.4.0-rc.9]
        at com.netflix.hystrix.AbstractCommand$5.call(AbstractCommand.java:497) [hystrix-core-1.4.0-rc.9.jar:1.4.0-rc.9]
        at rx.Observable.unsafeSubscribe(Observable.java:7466) [rxjava-1.0.7.jar:1.0.7]
        at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62) [rxjava-1.0.7.jar:1.0.7]
        at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:56) [hystrix-core-1.4.0-rc.9.jar:1.4.0-rc.9]
        at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:47) [hystrix-core-1.4.0-rc.9.jar:1.4.0-rc.9]
        at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction.call(HystrixContexSchedulerAction.java:69) [hystrix-core-1.4.0-rc.9.jar:1.4.0-rc.9]
        at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:47) [rxjava-1.0.7.jar:1.0.7]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_05]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_05]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_05]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_05]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_05]
Caused by: java.io.FileNotFoundException: http://localhost:11618/api/loanApplication/1
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1834) ~[na:1.8.0_05]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1439) ~[na:1.8.0_05]
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480) ~[na:1.8.0_05]
        at org.springframttp.client.SimpleClientHttpResponse.getRawStatusCode(SimpleClientHttpResponse.java:48) ~[spring-web-4.1.5.RELEASE.jar:4.1.5.RELEASE]
        at org.springframework.http.client.AbstractClientHttpResponse.getStatusCode(AbstractClientHttpResponse.java:33) ~[spring-web-4.1.5.RELEASE.jar:4.1.5.RELEASE]
        at org.springframework.http.client.BufferingClientHttpResponseWrapper.getStatusCode(BufferingClientHttpResponseWrapper.java:48) ~[spring-web-4.1.5.RELEASE.jar:4.1.5.RELEASE]
        at com.ofg.infrastructure.web.resttemplate.custom.ResponseRethrowingErrorHandler.hasError(ResponseRethrowingErrorHandler.groovy:21) [micro-infra-spring-base-0.7.888.jar:na]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:569) [spring-web-4.1.5.RELEASE.jar:4.1.5.RELEASE]
        ... 78 common frames omitted
2015-03-22 23:02:24.742+0100 | ERROR | 73c11548-5fd6-4c46-b871-e71064871197 | hystrix-fraudDetection-1 | c.o.i.w.r.c.ResponseRethrowingErrorHandler | Response error: status code [404], headers [[Content-Length:[0], Server:[Jetty(6.1.26)]]], body [null]
2015-03-22 23:02:24.762+0100 | INFO  | 73c11548-5fd6-4c46-b871-e71064871197 | SimpleAsyncTaskExecutor-1 | o.m.f.FraudDetectionService | result = dupa
```
