### ISSUE TITLE
hystrixFallback is not executed when requested service not registered in ZooKeeper

### ISSUE THREAD

**Issue by mkucharek** [4finance/micro-infra-spring#337]
Instead, a ServiceUnavailableException is being thrown The only reasonable way of dealing with it is to catch the exception in for each of the service call, as the hystrix fallback does not get executed in such a case. 

This was encountered during a hackaton, when running our service locally, with no other collabolators registered in ZooKeeper.

Sample code:
https://github.com/microhackathon-2015-03-juglodz/ui-waw/releases/tag/serviceUnavailableExceptionIssue

Stack trace:
```
com.ofg.infrastructure.discovery.ServiceUnavailableException: Service with name [com/ofg/client-service-waw] is unavailable
	at com.ofg.infrastructure.discovery.ZookeeperServiceResolver.fetchUri(ZookeeperServiceResolver.groovy:79) ~[micro-deps-0.8.14.jar:na]
	at com.ofg.infrastructure.web.resttemplate.fluent.ServiceRestClient.forService(ServiceRestClient.groovy:102) ~[micro-infra-spring-base-0.8.14.jar:na]
	at com.ofg.infrastructure.web.resttemplate.fluent.ServiceRestClient$forService.call(Unknown Source) ~[na:na]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45) [groovy-all-2.4.1.jar:2.4.1]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:110) [groovy-all-2.4.1.jar:2.4.1]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:122) [groovy-all-2.4.1.jar:2.4.1]
	at com.ofg.twitter.loan.LoanApplicationService.doCallClientService(LoanApplicationService.groovy:69) ~[main/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_05]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_05]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_05]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_05]
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:207) ~[groovy-all-2.4.1.jar:2.4.1]
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56) ~[groovy-all-2.4.1.jar:2.4.1]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49) [groovy-all-2.4.1.jar:2.4.1]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:151) [groovy-all-2.4.1.ja]:2.4.1
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:163) [groovy-all-2.4.1.jar:2.4.1]
	at com.ofg.twitter.loan.LoanApplicationService.sendClientDetails(LoanApplicationService.groovy:59) ~[main/:na]
	at com.ofg.twitter.loan.LoanApplicationService$sendClientDetails.call(Unknown Source) [main/:na]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45) [groovy-all-2.4.1.jar:2.4.1]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:110) [groovy-all-2.4.1.jar:2.4.1]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:122) [groovy-all-2.4.1.jar:2.4.1]
	at com.ofg.twitter.loan.LoanApplicationController.applyForLoan(LoanApplicationController.groovy:38) [main/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_05]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_05]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_05]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_05]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221) [spring-web-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137) [spring-web-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110) [spring-webmvc-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:777) [spring-webmvc-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:706) [spring-webmvc-4.1.5.RELEASE.jar:4.1.5.RELEASE]
    org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) [spring-webmvc-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:943) [spring-webmvc-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:877) [spring-webmvc-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:966) [spring-webmvc-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:868) [spring-webmvc-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:644) [tomcat-embed-core-8.0.20.jar:8.0.20]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:842) [spring-webmvc-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) [tomcat-embed-core-8.0.20.jar:8.0.20]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) [tomcat-embed-core-8.0.20.jar:8.0.20]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [tomcat-embed-core-8.0.20.jar:8.0.20]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-embed-websocket-8.0.20.jar:8.0.20]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [tomcat-embed-core-8.0.20.jar:8.0.20]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [tomcat-embed-core-8.0.20.jar:8.0.20]
	at org.springframework.boot.actuate.autoconfigure.EndpointWebMvcAutoConfiguration$ApplicationContextHeaderFilter.doFilterInternal(EndpointWebMvcAutoConfiguration.java:291) [spring-boot-actuator-1.2.2.RELEASE.jar:1.2.2.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter07) [spring-web-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [tomcat-embed-core-8.0.20.jar:8.0.20]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [tomcat-embed-core-8.0.20.jar:8.0.20]
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77) [spring-web-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [tomcat-embed-core-8.0.20.jar:8.0.20]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [tomcat-embed-core-8.0.20.jar:8.0.20]
	at com.ofg.infrastructure.web.correlationid.CorrelationIdFilter.doFilterInternal(CorrelationIdFilter.groovy:55) [micro-infra-spring-base-0.8.14.jar:na]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [tomcat-embed-core-8.0.20.jar:8.0.20]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [tomcat-embed-core-8.0.20.jar:8.0.20]
	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:102) [spring-boot-actuator-1.2.2.RELEASE.jar:1.2.2.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [tomcat-embed-core-8.0.20.jar:8.0.20]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [tomcat-embed-core-8.0.20.jar:8.0.20]
	at orgframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88) [spring-web-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [tomcat-embed-core-8.0.20.jar:8.0.20]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [tomcat-embed-core-8.0.20.jar:8.0.20]
	at org.springframework.boot.actuate.autoconfigure.MetricFilterAutoConfiguration$MetricsFilter.doFilterInternal(MetricFilterAutoConfiguration.java:90) [spring-boot-actuator-1.2.2.RELEASE.jar:1.2.2.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.1.5.RELEASE.jar:4.1.5.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [tomcat-embed-core-8.0.20.jar:8.0.20]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [tomcat-embed-core-8.0.20.jar:8.0.20]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [tomcat-embed-core-8.0.20.jar:8.0.20]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [tomcat-embed-core-8.0.20.jar:8.0.20]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501) [tomcat-embed-core-8.0.20.jar:8.0.20]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [tomcat-embed-core-8.0.20.jar:8.0.20]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [tomcat-embed-core-8.0.20.jar:8.0.20]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [tomcat-embed-core-8.0.20.jar:8.0.20]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516) [tomcat-embed-core-8.0.20.jar:8.0.20]
	at org.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086) [tomcat-embed-core-8.0.20.jar:8.0.20]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659) [tomcat-embed-core-8.0.20.jar:8.0.20]
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223) [tomcat-embed-core-8.0.20.jar:8.0.20]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558) [tomcat-embed-core-8.0.20.jar:8.0.20]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515) [tomcat-embed-core-8.0.20.jar:8.0.20]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_05]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_05]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.0.20.jar:8.0.20]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_05]
```

The only way of handling such problem is to catch the exception for each service call.

**Comment by marcingrzejszczak** [comment]
@mkucharek - thanks for the issue! Maybe you would like to create a PR for that? :P

**Comment by marcingrzejszczak** [comment]
@mkucharek  - I've just built a version of micro-infra-spring from the PR - https://github.com/4finance/micro-infra-spring/pull/340 and ran your UI-WAW from the hackathon. That's what I got in the log

```
2015-03-22 22:04:50.240+0100 | DEBUG | 08a236a5-eb1f-44fc-a441-9387c41e9b7c | hystrix-sendingLoanDetails-1 | c.n.h.AbstractCommand | Error executing HystrixCommand.run(). Proceeding to fallback logic ...
com.ofg.infrastructure.discovery.ServiceUnavailableException: Service with name [com/ofg/loan-application-service-waw] is unavailable
	at com.ofg.infrastructure.discovery.ZookeeperServiceResolver.fetchUri(ZookeeperServiceResolver.groovy:79) ~[micro-deps-0.7.999.jar:na]
	at com.ofg.infrastructure.web.resttemplate.fluent.ServiceRestClient$_getServiceUri_closure1.doCall(ServiceRestClient.groovy:110) ~[micro-infra-spring-base-0.7.999.jar:na]
	at com.ofg.infrastructure.web.resttemplate.fluent.ServiceRestClient$_getServiceUri_closure1.doCall(ServiceRestClient.groovy) ~[micro-infra-spring-base-0.7.999.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_05]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_05]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_05]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_05]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90) ~[groovy-all-2.4.1.jar:2.4.1]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324) ~[groovy-all-2.4.1.jar:2.4.1]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292) ~[groovy-all-2.4.1.jar:2.4.1]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016) ~[groovy-all-2.4.1.jar:2.4.1]
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39) ~[groovy-all-2.4.1.jar:2.4.1]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:114) ~[groovy-all-2.4.1.jar:2.4.1]
	at com.ofg.infrastructure.web.resttemplate.fluent.common.response.executor.RestExecutor.getHost(RestExecutor.groovy:85) ~[micro-infra-spring-base-0.7.999.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invokee Method) ~[na:1.8.0_05]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_05]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_05]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_05]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90) ~[groovy-all-2.4.1.jar:2.4.1]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324) ~[groovy-all-2.4.1.jar:2.4.1]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:382) ~[groovy-all-2.4.1.jar:2.4.1]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016) ~[groovy-all-2.4.1.jar:2.4.1]
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:66) ~[groovy-all-2.4.1.jar:2.4.1]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:163) ~[groovy-all-2.4.1.jar:2.4.1]
	at com.ofg.infrastructure.web.resttemplate.fluent.common.response.executor.RestExecutor$_urlExchange_closure2.doCall(RestExecutor.groovy:91) ~[micro-infra-spring-base-0.7.999.jar:na]
	at com.ofg.infrastructure.web.resttemplate.fluent.common.response.executor.RestExecutor$_urlExchange_closure2.doCall(RestExecutor.groovy) ~[micro-infra-spring-base-0.7.999.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_05]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_05]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_05]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_05]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90) ~[groovy-all-2.4.1.jar:2.4.1]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324) ~[groovy-all-2.4.1.jar:2.4.1]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292) ~[groovy-all-2.4.1.jar:2.4.1]
	at groovy.lang.MetaCl.invokeMethod(MetaClassImpl.java:1016) ~[groovy-all-2.4.1.jar:2.4.1]
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39) ~[groovy-all-2.4.1.jar:2.4.1]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:114) ~[groovy-all-2.4.1.jar:2.4.1]
	at com.ofg.infrastructure.web.resttemplate.fluent.common.response.executor.RestExecutor$1.doRun(RestExecutor.groovy:121) ~[micro-infra-spring-base-0.7.999.jar:na]
	at com.ofg.infrastructure.web.resttemplate.fluent.common.response.executor.RestExecutor$1.doRun(RestExecutor.groovy) ~[micro-infra-spring-base-0.7.999.jar:na]
	at com.ofg.infrastructure.hystrix.CorrelatedCommand$_run_closure1.doCall(CorrelatedCommand.groovy:25) ~[micro-infra-spring-base-0.7.999.jar:na]
	at com.ofg.infrastructure.hystrix.CorrelatedCommand$_run_closure1.call(CorrelatedCommand.groovy) ~[micro-infra-spring-base-0.7.999.jar:na]
	at com.ofg.infrastructure.correlationid.CorrelationIdUpdater.withId(CorrelationIdUpdater.groovy:45) ~[micro-infra-spring-base-0.7.999.jar:na]
	at com.ofg.infrastructure.hystrix.CorrelatedCommand.run(CorrelatedCommand.groovy:24) ~[micro-infra-spring-base-0.7.999.jar:na]
	at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:294) [hystrix-core-1.4.0-rc.9.jar:1.4.0-rc.9]
	at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:289) [hystrix-core-1.4.0-rc.9.jar:1.4.0-rc.9]
	at rx.Observable$1.call(Observable.java:144) [rxjava-1.0.7.jar:1.0.7]
	at rx.Observable$1.call(Observable.java:136) [rxjava-1.0.7.jar:1.0.7]
	at rx.Observable$1.call(Observable.java:144) [rxjava-1.0.7.jar:1.0.7]
	at rx.Observable$1.call(Observable.java:136) [rxjava-1.0.7.jar:1.0.7]
	at rx.Observable$1.call(Observable.java:144) [rxjava-1.0.7.jar:1.0.7]
	at rx.Observable$1.call(Observable.java:136) [rxjava-1.0.7.jar:1.0.7]
	at rx.Observable.unsafeSubscribe(Observable.java:7466) [rxjava-1.0.7.jar:1.0.7]
	at com.netflix.hystrix.AbstractCommand$5.call(AbstractCommand.java:514) [hystrix-core-1.4.0-rc.9.jar:1.4.0-rc.9]
	at clix.hystrix.AbstractCommand$5.call(AbstractCommand.java:497) [hystrix-core-1.4.0-rc.9.jar:1.4.0-rc.9]
	at rx.Observable.unsafeSubscribe(Observable.java:7466) [rxjava-1.0.7.jar:1.0.7]
	at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62) [rxjava-1.0.7.jar:1.0.7]
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:56) [hystrix-core-1.4.0-rc.9.jar:1.4.0-rc.9]
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:47) [hystrix-core-1.4.0-rc.9.jar:1.4.0-rc.9]
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction.call(HystrixContexSchedulerAction.java:69) [hystrix-core-1.4.0-rc.9.jar:1.4.0-rc.9]
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:47) [rxjava-1.0.7.jar:1.0.7]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_05]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_05]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_05]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_05]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_05]
2015-03-22 22:04:50.241+0100 | INFO  | 08a236a5-eb1f-44fc-a441-9387c41e9b7c | hystrix-sendingLoanDetails-1 | c.o.t.l.LoanApplicationService | Breaking circuit
```

So it was in the Hystrix thread that the exception was thrown and the fallback logic worked. In swagger 200 was returned:

```
Request URL
http://localhost:8080/loan

Response Body
no content

Response Code
200

Response Headers
{
  "Correlationid": "08a236a5-eb1f-44fc-a441-9387c41e9b7c",
  "Date": "Sun, 22 Mar 2015 21:04:50 GMT",
  "Server": "Apache-Coyote/1.1",
  "Content-Length": "0",
  "X-Application-Context": "bootstrap:dev"
}
```

**Comment by mkucharek** [comment]
thanks Marcin, I guess it works as it should right now ;)

**Comment by marcingrzejszczak** [comment]
try it on production and tell us :D
