### ISSUE TITLE
Flickering test - CorrelationIdAspectSpec - ResourceAccessException: I/O error on GET request for "http://localhost:9573"

### ISSUE THREAD

**Issue by szpak** [4finance/micro-infra-spring#359]
Recently `CorrelationIdAspectSpec` started to fail often [on Travis](https://travis-ci.org/4finance/micro-infra-spring/jobs/56019201#L444) and the build has to be restarted. It could be investigated.

```
:micro-infra-spring-base:test

com.ofg.infrastructure.web.correlationid.CorrelationIdAspectSpec > should set correlationId on header via aspect in synchronous call FAILED

org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://localhost:9573":Read timed out; nested exception is java.net.SocketTimeoutException: Read timed out
at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:978)
at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:857)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:618)
at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:842)
at org.springframework.test.web.servlet.TestDispatcherServlet.service(TestDispatcherServlet.java:65)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
at org.springframework.mock.web.MockFilterChain$ServletFilterProxy.doFilter(MockFilterChain.java:167)
at org.springframework.mock.web.MockFilterChain.doFilter(MockFilterChain.java:134)
at com.ofg.infrastructure.web.correlationid.CorrelationIdFilter.doFilterInternal(CorrelationIdFilter.groovy:55)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
at org.springframework.mock.web.MockFilterChain.doFilter(MockFilterChain.java:134)
at org.springframework.test.web.servlet.MockMvc.perform(MockMvc.java:144)
at com.ofg.infrastructure.web.correlationid.CorrelationIdAspectSpec.should set correlationId on header via aspect in synchronous call(CorrelationIdAspectSpec.groovy:45)

Caused by:
org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://localhost:9573":Read timed out; nested exception is java.net.SocketTimeoutException: Read timed out
at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:584)
at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:544)
at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:465)
at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85)
at com.ofg.infrastructure.web.resttemplate.MetricsAspect.measureRestCallDuration_closure1(MetricsAspect.groovy:32)
at com.codahale.metrics.Timer.time(Timer.java:101)
at com.ofg.infrastructure.web.resttemplate.MetricsAspect.measureRestCallDuration(MetricsAspect.groovy:30)
at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:621)
at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:610)
at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:68)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:97)
at com.ofg.infrastructure.web.correlationid.CorrelationIdAspect.wrapWithCorrelationIdForRestOperations(CorrelationIdAspect.groovy:82)
at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:621)
at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:610)
at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:68)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
at com.ofg.infrastructure.web.resttemplate.fluent.common.response.executor.RestExecutor.urlExchange_closure2(RestExecutor.groovy:96)
at com.ofg.infrastructure.web.resttemplate.fluent.common.response.executor.RestExecutor.urlExchange_closure2(RestExecutor.groovy)
at com.ofg.infrastructure.web.resttemplate.fluent.common.response.executor.RestExecutor.callHttp(RestExecutor.groovy:114)
at com.ofg.infrastructure.web.resttemplate.fluent.common.response.executor.RestExecutor.withRetry_closure3$_closure4(RestExecutor.groovy:105)
at com.ofg.infrastructure.web.resttemplate.fluent.common.response.executor.RestExecutor.withRetry_closure3$_closure4(RestExecutor.groovy)
at groovy.lang.Closure.call(Closure.java:423)
at groovy.lang.Closure.call(Closure.java:417)
at com.ofg.infrastructure.correlationid.CorrelationIdUpdater.withId(CorrelationIdUpdater.groovy:45)
at com.ofg.infrastructure.web.resttemplate.fluent.common.response.executor.RestExecutor.withRetry_closure3(RestExecutor.groovy:104)
at com.ofg.infrastructure.web.resttemplate.fluent.common.response.executor.RestExecutor.withRetry_closure3(RestExecutor.groovy)
at groovy.lang.Closure.call(Closure.java:423)
at groovy.lang.Closure.call(Closure.java:417)
at com.nurkiewicz.asyncretry.SyncRetryExecutor.getWithRetry(SyncRetryExecutor.java:37)
at com.ofg.infrastructure.web.resttemplate.fluent.common.response.executor.RestExecutor.withRetry(RestExecutor.groovy:103)
at com.ofg.infrastructure.web.resttemplate.fluent.common.response.executor.RestExecutor.urlExchange(RestExecutor.groovy:92)
at com.ofg.infrastructure.web.resttemplate.fluent.common.response.executor.RestExecutor.exchangeInternal(RestExecutor.groovy:63)
at com.ofg.infrastructure.web.resttemplate.fluent.common.response.executor.RestExecutor.exchange(RestExecutor.groovy:43)
at com.ofg.infrastructure.web.resttemplate.fluent.common.response.executor.ResponseTypeRelatedRequestsExecutor.exchange(ResponseTypeRelatedRequestsExecutor.groovy:41)
at com.ofg.infrastructure.web.resttemplate.fluent.get.GetMethodBuilder$2.ofType(GetMethodBuilder.groovy:77)
at com.ofg.infrastructure.web.correlationid.CorrelationIdAspectSpec$CorrelationIdAspectSpecConfiguration$AspectTestingController.callWiremockAndReturnOk(CorrelationIdAspectSpec.groovy:95)
at com.ofg.infrastructure.web.correlationid.CorrelationIdAspectSpec$CorrelationIdAspectSpecConfiguration$AspectTestingController.syncPing(CorrelationIdAspectSpec.groovy:82)
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653)
at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:777)
at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:706)
at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:943)
at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:877)
at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:966)
... 12 more

Caused by:
java.net.SocketTimeoutException: Read timed out
at java.net.SocketInputStream.read(SocketInputStream.java:152)
at java.net.SocketInputStream.read(SocketInputStream.java:122)
at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
at java.io.BufferedInputStream.read1(BufferedInputStream.java:275)
at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:689)
at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:633)
at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1324)
at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
at org.springframework.http.client.SimpleClientHttpResponse.getRawStatusCode(SimpleClientHttpResponse.java:48)
at org.springframework.http.client.AbstractClientHttpResponse.getStatusCode(AbstractClientHttpResponse.java:33)
at org.springframework.http.client.BufferingClientHttpResponseWrapper.getStatusCode(BufferingClientHttpResponseWrapper.java:48)
at com.ofg.infrastructure.web.resttemplate.custom.ResponseRethrowingErrorHandler.hasError(ResponseRethrowingErrorHandler.groovy:21)
at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:569)
... 70 more
```

**Comment by kamilszymanski** [comment]
Maybe those problems were related to [DDoS attack on GitHub](https://github.com/blog/1981-large-scale-ddos-attack-on-github-com)

**Comment by szpak** [comment]
The problems with cloning the repository possibly, but here we have tests running on Travis which tries to connect to localhost (our service set up for tests), so I doubt.

**Comment by kamilszymanski** [comment]
Maybe this DDoS also affected Travis CI and during DDoS you can expect some timeouts (I guess even on localhost - a socket is a socket)
```
Caused by:
java.net.SocketTimeoutException: Read timed out
```

**Comment by marcingrzejszczak** [comment]
Not related anymore
