### ISSUE TITLE
Make spring-infra-spring-config compatible with spring-cloud-config 1.0.1

### ISSUE THREAD

**Issue by szpak** [4finance/micro-infra-spring#386]
Minor change (1.0.0 -> 1.0.1), but with lot of internal changes. Some of them affect us. LoadingFromFileSystemSpec fails with:
```
Caused by: java.lang.IllegalArgumentException:
Could not resolve placeholder 'global.prop.key' in string value "${global.prop.key}"
```
After some debugging it seems that `NativeEnvironmentRepository` (as replacement of `SpringApplicationEnvironmentRepository`) doesn't like extract files passed as serchLocaltions and add `/` to them. That causes that configured properties are not read.

**Comment by marcingrzejszczak** [comment]
I have the same exception in 1.0.2 and I think I can't use 1.0.0.M1 Milestone of Spring CLoud Zookeeper without this

**Comment by marcingrzejszczak** [comment]
The exception is as follows when I start boot-microservice from the zookeeper migration branch:

```
java.lang.NoClassDefFoundError: org/springframework/boot/context/config/ConfigFileApplicationListener
	at org.springframework.cloud.config.server.SpringApplicationEnvironmentRepository.findOne(SpringApplicationEnvironmentRepository.java:73) ~[spring-cloud-config-server-1.0.0.RELEASE.jar:1.0.0.RELEASE]
	at com.ofg.infrastructure.property.FileSystemLocator.locate(FileSystemLocator.java:41) ~[micro-infra-spring-config-0.0.1-SNAPSHOT.jar:na]
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:81) ~[spring-cloud-config-client-1.0.0.RELEASE.jar:1.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:562) ~[spring-boot-1.3.0.M5.jar:1.3.0.M5]
	at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:324) ~[spring-boot-1.3.0.M5.jar:1.3.0.M5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:273) ~[spring-boot-1.3.0.M5.jar:1.3.0.M5]
	at org.springframework.boot.SpringApplication$run.call(Unknown Source) [spring-boot-1.3.0.M5.jar:1.3.0.M5]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45) [groovy-all-2.4.3.jar:2.4.3]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:110) [groovy-all-2.4.3.jar:2.4.3]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:122) [groovy-all-2.4.3.jar:2.4.3]
	at com.ofg.twitter.Application.main(Application.groovy:21) [main/:na]
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.context.config.ConfigFileApplicationListener
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_45]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_45]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[na:1.8.0_45]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_45]
	... 11 common frames omitted
2015-09-09 08:11:32.630+0200 | ERROR |  | main | o.a.z.s.NIOServerCnxnFactory | Thread Thread[main,5,main] died
java.lang.NoClassDefFoundError: org/springframework/boot/context/config/ConfigFileApplicationListener
	at org.springframework.cloud.config.server.SpringApplicationEnvironmentRepository.findOne(SpringApplicationEnvironmentRepository.java:73) ~[spring-cloud-config-server-1.0.0.RELEASE.jar:1.0.0.RELEASE]
	at com.ofg.infrastructure.property.FileSystemLocator.locate(FileSystemLocator.java:41) ~[micro-infra-spring-config-0.0.1-SNAPSHOT.jar:na]
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:81) ~[spring-cloud-config-client-1.0.0.RELEASE.jar:1.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:562) ~[spring-boot-1.3.0.M5.jar:1.3.0.M5]
	at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:324) ~[spring-boot-1.3.0.M5.jar:1.3.0.M5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:273) ~[spring-boot-1.3.0.M5.jar:1.3.0.M5]
	at org.springframework.boot.SpringApplication$run.call(Unknown Source) ~[na:na]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45) ~[groovy-all-2.4.3.jar:2.4.3]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:110) ~[groovy-all-2.4.3.jar:2.4.3]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:122) ~[groovy-all-2.4.3.jar:2.4.3]
	at com.ofg.twitter.Application.main(Application.groovy:21) ~[main/:na]
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.context.config.ConfigFileApplicationListener
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_45]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_45]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[na:1.8.0_45]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_45]
	... 11 common frames omitted
```

**Comment by marcingrzejszczak** [comment]
Already done https://github.com/4finance/micro-infra-spring/issues/521
