### ISSUE TITLE
Missing guava dependency

### ISSUE THREAD

**Issue by mariuszs** [4finance/micro-infra-spring#415]
Minimal project with:

```
        <dependency>
            <groupId>com.ofg</groupId>
            <artifactId>micro-infra-spring-boot-starter</artifactId>
            <version>0.8.19</version>
        </dependency>
```

throws exception:

```
SLF4J: Failed toString() invocation on an object of type [com.ofg.infrastructure.property.ConfigLocations]
java.lang.NoClassDefFoundError: com/google/common/base/MoreObjects
	at com.ofg.infrastructure.property.ConfigLocations.toString(ConfigLocations.java:78)
	at org.slf4j.helpers.MessageFormatter.safeObjectAppend(MessageFormatter.java:297)
	at org.slf4j.helpers.MessageFormatter.deeplyAppendParameter(MessageFormatter.java:269)
	at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:227)
	at ch.qos.logback.classic.spi.LoggingEvent.getFormattedMessage(LoggingEvent.java:298)
	at ch.qos.logback.classic.spi.LoggingEvent.prepareForDeferredProcessing(LoggingEvent.java:208)
	at ch.qos.logback.core.OutputStreamAppender.subAppend(OutputStreamAppender.java:212)
	at ch.qos.logback.core.OutputStreamAppender.append(OutputStreamAppender.java:103)
	at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:88)
	at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:48)
	at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:273)
	at ch.qos.logback.classic.Logger.callAppenders(Logger.java:260)
	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:442)
	at ch.qos.logback.classic.Logger.filterAndLog_1(Logger.java:414)
	at ch.qos.logback.classic.Logger.info(Logger.java:604)
	at com.ofg.infrastructure.property.FileSystemPoller$PollerRunnable.run(FileSystemPoller.java:100)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.google.common.base.MoreObjects
```

**Comment by mariuszs** [comment]
Ok, it is not missing. Gradle is not reporting not accessible artifact.

**Comment by mariuszs** [comment]
cannot reproduce
