### ISSUE TITLE
Verification of interactions with stubs doesn't work

### ISSUE THREAD

**Issue by mchmielarz** [4finance/micro-infra-spring#434]
It is not possible to verify interactions with stubs for integration tests based on `MvcWiremockIntegrationSpec`. `MissingStubException` is thrown with following stack trace:

```
Missing stub for collaborator name: stubXYZ
com.ofg.infrastructure.stub.MissingStubException: Missing stub for collaborator name: stubXYZ
	at com.ofg.infrastructure.stub.Stubs.findCollaboratorStubUrl_closure4(Stubs.groovy:47)
	at com.ofg.infrastructure.stub.Stubs.findCollaboratorStubUrl_closure4(Stubs.groovy)
	at groovy.lang.Closure.call(Closure.java:423)
	at com.google.common.base.Absent.or(Absent.java:60)
	at com.ofg.infrastructure.stub.Stubs.findCollaboratorStubUrl(Stubs.groovy:47)
	at com.ofg.infrastructure.stub.Stubs.createNewStub(Stubs.groovy:34)
	at com.ofg.infrastructure.stub.Stubs$_closure1.doCall(Stubs.groovy:13)
	at groovy.lang.Closure.call(Closure.java:423)
	at groovy.lang.MapWithDefault.get(MapWithDefault.java:60)
	at com.ofg.infrastructure.stub.Stubs.of(Stubs.groovy:21)
	at com.ofg.infrastructure.base.MvcWiremockIntegrationSpec.stubOf(MvcWiremockIntegrationSpec.groovy:46)
```

**Comment by mchmielarz** [comment]
It seems the problem is caused by setting `ThreadLocal<StubRunnerExecutor> stubRunnerContainer` in `com.ofg.stub.StubRunner`.

In case of two or more dependencies defined in microservice file `StubRunnerExecutor` of the second and every next dependency overrides `stubRunnerContainer` content. Verification of interactions required to find defined mock of given dependency and this mock is always searched in `StubRunnerExecutor` that was set as the last one in `stubRunnerContainer` field.

In this situation I just wonder what is the purpose of using `ThreadLocal` in `StubRunner` class? Do we need it at all? @marcingrzejszczak @nurkiewicz @szpak @kamilszymanski

**Comment by marcingrzejszczak** [comment]
AFAIR we wanted to tackle potential thread safety issues but maybe it was
completely unnecessary. WDYT @kamilszymanski?

**Comment by mchmielarz** [comment]
I've just run tests with `ThreadLocal` removed and it worked. But this is just for my project only.

**Comment by marcingrzejszczak** [comment]
Ok so go for it and do the PR. I don't think that it should do any harm ;)

**Comment by mchmielarz** [comment]
Changed & merged.
