### ISSUE TITLE
ServiceRestClient.forService throws IllegalStateException  

### ISSUE THREAD

**Issue by jac0by** [4finance/micro-infra-spring#443]
We're working with ServiceRestClient to perform cross services calls. And once we started to use it more intensively the following exception appeared in our logs:

```
java.lang.IllegalStateException: Already closed or has not been started
	at com.google.common.base.Preconditions.checkState(Preconditions.java:149)
	at org.apache.curator.x.discovery.details.ServiceCacheImpl.close(ServiceCacheImpl.java:91)
	at org.apache.curator.x.discovery.details.ServiceProviderImpl.close(ServiceProviderImpl.java:78)
	at com.ofg.infrastructure.discovery.ZookeeperServiceResolver.providerFor(ZookeeperServiceResolver.java:219)
	at com.ofg.infrastructure.discovery.ZookeeperServiceResolver.resolveServiceAddress(ZookeeperServiceResolver.java:202)
	at com.ofg.infrastructure.discovery.ZookeeperServiceResolver.fetchUri(ZookeeperServiceResolver.java:108)
```

Most likely it's caused by non-threadsafe method com.ofg.infrastructure.discovery.ZookeeperServiceResolver.providerFor.

The micro-infra-spring version is 0.8.21

**Comment by marcingrzejszczak** [comment]
In progress in PR #445
