### ISSUE TITLE
 Premature end of file for Obfuscator - not harmful 

### ISSUE THREAD

**Issue by maciekpe** [4finance/micro-infra-spring#539]
For some calls with empty body we can meet such problem :

org.xml.sax.SAXParseException: Premature end of file.
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source) ~[xercesImpl-2.9.1.jar!/:na]
        at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source) ~[xercesImpl-2.9.1.jar!/:na]
        at groovy.util.XmlSlurper.parse(XmlSlurper.java:207) ~[groovy-all-2.4.5-indy.jar!/:2.4.5]
        at groovy.util.XmlSlurper.parse(XmlSlurper.java:260) ~[groovy-all-2.4.5-indy.jar!/:2.4.5]
        at groovy.util.XmlSlurper.parseText(XmlSlurper.java:286) ~[groovy-all-2.4.5-indy.jar!/:2.4.5]
        at groovy.util.XmlSlurper$parseText.call(Unknown Source) ~[na:na]
        at com.ofg.infrastructure.web.logging.obfuscation.XmlPayloadObfuscator.cleanFieldsFromXml(XmlPayloadObfuscator.groovy:22) ~[micro-infra-spring-base-0.9.8.jar!/:na]

**Comment by maciekpe** [comment]
Fixed in legacy & master
